### ISSUE TITLE
Root redirects to 404 when deploying / running netlify dev

### ISSUE THREAD

**Issue by nejcukmar** [FinnWoelm/next-on-netlify#28]
Don't know exactly if this is next-on-netlify issue or if it's related to netlify-cli.

Basically after running dev version on localhost or even deploying to netlify and visiting served page, you are automatically redirected to 404.

Here is how I managed to encounter a problem:
1. Cloning https://github.com/FinnWoelm/next-on-netlify-demo
2. Installing npm packages
3. npm run build
4. netlify dev

Visiting any page over URL directly (except index) works as expected, even navigation over all pages after works normally. The only problem is direct visit to /.

Anyone else experiencing this?

**Comment by FinnWoelm** [comment]
Hi @nejcukmar,

Thanks for checking out `next-on-netlify` and thank you for your message.

The demo repository https://github.com/FinnWoelm/next-on-netlify-demo is not set up for local previewing with `netlify dev`. You have to do a few extra steps:

First, install the latest version of `netlify-cli` (currently, that's v2.58 — you can run `netlify --version` to confirm):

```bash
npm install -g netlify-cli
```
 
Then, add the following `[dev]` block to your `netlify.toml`:

```toml
# netlify.toml

# [build]
#   ...

[dev]
  functions = "out_functions"
  publish   = "out_publish"
  # We manually set the framework to static, otherwise Netlify automatically
  # detects NextJS and redirects do not work.
  # Read more: https://github.com/netlify/cli/blob/master/docs/netlify-dev.md#project-detection
  framework = "#static"
```

Lastly, add the following lines to your `.gitignore`:

```shell
# .gitignore

# Files generated by next-on-netlify command
/out_publish/
/out_functions/
/404.html
```

Now you're all set. Run `npm run build` and `netlify dev` and everything should work :blush: 

Let me know if you run into any issues!
